### PR TITLE
add favicon and use https on link

### PR DESCRIPTION
**Pull request by lpmi-13**
figured we could just use the same brand logo for the favicon.

### CODE REVIEW

**Comment by lpmi-13** [comment]
...also was thinking of opening a PR to enable dev on this locally, but if nobody really cares then fair enough.

**Comment by unlobito** [comment]
> ...also was thinking of opening a PR to enable dev on this locally, but if nobody really cares then fair enough.

👋 definitely would be useful! what sort of things would that cover?

**Comment by lpmi-13** [comment]
well the biggest thing was the fetching of assets off of the /vendor subpath, which doesn't exist locally, so the bare minimum easy win is just to add in those assets to the repo itself.

Another option (if the preference is to keep those separate and out of the repo), would involve adding in a build tool like gulp(easier/lighter) or webpack(way heavier) to conditionally write the asset paths in the index.html, though this would probably affect the way that you deploy the current site.

...and then I'd probably also add some simple instructions in the readme for how to fire it up and run tests (probably no unit tests, but some simple security and accessibility ones might be nice).

**Comment by unlobito** [comment]
makes sense! @Samiser might also be able to sync the repo with the current website at https://hacksoc.co.uk/ since the repo seems a bit out of date.

@rossdonald97 do you remember how you built the vendor directory for this?

**Pull request merged**
